SET SERVEROUTPUT ON;
DECLARE
    CURSOR C1 IS SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DEFAULT_LENGTH, DATA_DEFAULT FROM ALL_TAB_COLUMNS WHERE OWNER= '&1' ORDER BY 1,2,3;
BEGIN
    DBMS_OUTPUT.ENABLE(3000000);
    DBMS_OUTPUT.PUT_LINE('sql.tabcoldefaults');
	DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------------');

    DBMS_OUTPUT.PUT_LINE('TABLE_NAME,COLUMN_NAME,DATA_TYPE,DATA_DEFAULT');
    FOR COL IN C1 LOOP
    IF LENGTH(TRIM(COL.DATA_DEFAULT)) > 0 THEN
        DBMS_OUTPUT.PUT_LINE (COL.TABLE_NAME ||','|| COL.COLUMN_NAME || ',' ||COL.DATA_TYPE||','|| TRIM(COL.DATA_DEFAULT));
    END IF;
    END LOOP;
END;
/
exit;