set heading off
set linesize 32767
set pagesize 50000
set AUTOP off
set feedback off

select 'details' from dual;
select '----------------------' from dual;
select version, instance_name, host_name from V$INSTANCE;

select 'xe.objects' from dual;
SELECT OBJECT_NAME||','|| nvl(SUBOBJECt_NAME,'<null>')||','||OBJECT_TYPE||','||STATUS||','||TEMPORARY||','||GENERATED||','||SECONDARY FROM DBA_OBJECTS WHERE OWNER = '&1' ORDER BY OBJECT_TYPE, OBJECT_NAME;

select 'xe.tables' from dual;
SELECT TABLE_NAME||','||TABLESPACE_NAME||','||nvl(CLUSTER_NAME,'<null>')||','||nvl(IOT_NAME,'<null>')||','||PCT_FREE||','||INI_TRANS||','||MAX_TRANS||','||MIN_EXTENTS||','||MAX_EXTENTS||','||PCT_INCREASE||','||LOGGING||','||DEGREE||','||INSTANCES||','||CACHE||','||TABLE_LOCK||','||PARTITIONED||','||nvl(IOT_TYPE,'<null>')||','||NESTED||','||BUFFER_POOL||','||ROW_MOVEMENT||','||USER_STATS||','||SKIP_CORRUPT FROM DBA_TABLES WHERE OWNER = '&1' ORDER BY TABLE_NAME;

select 'xe.tablecols' from dual;
SELECT TABLE_NAME||','||COLUMN_NAME||','||DATA_TYPE||','||DATA_TYPE_MOD||','||DATA_TYPE_OWNER||','||DATA_LENGTH||','||DATA_PRECISION||','||DATA_SCALE||','||NULLABLE||','||COLUMN_ID||','||CHAR_COL_DECL_LENGTH||','||USER_STATS||','||nvl(CHAR_LENGTH,'0') CHAR_LENGTH FROM DBA_TAB_COLUMNS WHERE DATA_TYPE != 'VARCHAR2' AND DATA_TYPE != 'CHAR' AND OWNER = '&1' ORDER BY DATA_TYPE, TABLE_NAME, COLUMN_NAME;

select 'xe.char' from dual;
SELECT TABLE_NAME||','||COLUMN_NAME||','||DATA_TYPE||','||DATA_TYPE_MOD||','||DATA_TYPE_OWNER||','||(DATA_LENGTH/4)||','||DATA_PRECISION||','||DATA_SCALE||','||NULLABLE||','||COLUMN_ID||','||(CHAR_COL_DECL_LENGTH/4)||','||USER_STATS||','||nvl(CHAR_LENGTH,'0') CHAR_LENGTH FROM DBA_TAB_COLUMNS WHERE DATA_TYPE='CHAR' AND OWNER = '&1' ORDER BY TABLE_NAME, COLUMN_NAME;

select 'xe.varchar' from dual;
SELECT TABLE_NAME||','||COLUMN_NAME||','||DATA_TYPE||','||DATA_TYPE_MOD||','||DATA_TYPE_OWNER||','||(DATA_LENGTH/4)||','||DATA_PRECISION||','||DATA_SCALE||','||NULLABLE||','||COLUMN_ID||','||(CHAR_COL_DECL_LENGTH/4)||','||USER_STATS||','||nvl(CHAR_LENGTH,'0') CHAR_LENGTH FROM DBA_TAB_COLUMNS WHERE DATA_TYPE='VARCHAR2' AND CHAR_LENGTH<1000 AND OWNER = '&1' ORDER BY TABLE_NAME, COLUMN_NAME;

select 'xe.varcharMX' from dual;
SELECT TABLE_NAME||','||COLUMN_NAME||','||DATA_TYPE||','||DATA_TYPE_MOD||','||DATA_TYPE_OWNER||','||DATA_LENGTH||','||DATA_PRECISION||','||DATA_SCALE||','||NULLABLE||','||COLUMN_ID||','||CHAR_COL_DECL_LENGTH||','||USER_STATS||','||nvl(CHAR_LENGTH,'0') CHAR_LENGTH FROM DBA_TAB_COLUMNS WHERE DATA_TYPE='VARCHAR2' AND CHAR_LENGTH>=1000 AND OWNER = '&1' ORDER BY TABLE_NAME, COLUMN_NAME;

select 'xe.constraints_1' from dual;
SELECT UC.OWNER||','|| UC.TABLE_NAME||','|| UC.CONSTRAINT_NAME ||','|| UCC.COLUMN_NAME||','|| UCC.POSITION||','|| UC.CONSTRAINT_TYPE||','|| UC.R_OWNER||','|| UC.R_CONSTRAINT_NAME||','|| UC.DELETE_RULE||','|| UC.STATUS||','|| UC.DEFERRABLE||','|| UC.DEFERRED||','|| UC.VALIDATED||','|| UC.GENERATED||','|| UC.BAD||','||UC.RELY||','|| UC.INDEX_OWNER||','|| UC.INDEX_NAME||','|| UC.INVALID||','|| UC.VIEW_RELATED FROM DBA_CONSTRAINTS UC, DBA_CONS_COLUMNS UCC WHERE (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME AND UC.OWNER = UCC.OWNER AND UC.TABLE_NAME = UCC.TABLE_NAME) AND UC.CONSTRAINT_NAME NOT LIKE 'SYS%' AND UC.OWNER = '&1' ORDER BY UC.OWNER, UC.TABLE_NAME, UCC.COLUMN_NAME, UC.CONSTRAINT_NAME;

select 'xe.constraints_1_sys' from dual; 
SELECT UC.OWNER||','|| UC.TABLE_NAME||','|| SUBSTR(UC.CONSTRAINT_NAME,0,7)||'_NUM' ||','|| UCC.COLUMN_NAME||','|| UCC.POSITION||','|| UC.CONSTRAINT_TYPE||','|| UC.R_OWNER||','|| UC.R_CONSTRAINT_NAME||','|| UC.DELETE_RULE||','|| UC.STATUS||','|| UC.DEFERRABLE||','|| UC.DEFERRED||','|| UC.VALIDATED||','|| UC.GENERATED||','|| UC.BAD||','||UC.RELY||','|| UC.INDEX_OWNER||','|| UC.INDEX_NAME||','|| UC.INVALID||','|| UC.VIEW_RELATED FROM DBA_CONSTRAINTS UC, DBA_CONS_COLUMNS UCC WHERE (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME AND UC.OWNER = UCC.OWNER AND UC.TABLE_NAME = UCC.TABLE_NAME) AND UC.CONSTRAINT_NAME LIKE 'SYS%' AND UC.OWNER = '&1' ORDER BY UC.OWNER, UC.TABLE_NAME, UCC.COLUMN_NAME, UC.CONSTRAINT_NAME;

select 'xe.constraints_2' from dual;
SELECT OWNER||','||TABLE_NAME||','|| CONSTRAINT_NAME ||','||CONSTRAINT_TYPE||','||R_OWNER||','||R_CONSTRAINT_NAME||','||DELETE_RULE||','||STATUS||','||DEFERRABLE||','||DEFERRED||','||VALIDATED||','||GENERATED||','||BAD||','||RELY||','||INDEX_OWNER||','||INDEX_NAME||','||INVALID||','||VIEW_RELATED FROM DBA_CONSTRAINTS WHERE CONSTRAINT_NAME IN (select distinct(CONSTRAINT_NAME) FROM DBA_CONSTRAINTS MINUS select Distinct(CONSTRAINT_NAME) FROM DBA_CONS_COLUMNS) AND CONSTRAINT_NAME NOT LIKE 'SYS%' AND OWNER = '&1' ORDER BY OWNER, TABLE_NAME, CONSTRAINT_NAME;

select 'xe.constraints_2_sys' from dual;
SELECT OWNER||','||TABLE_NAME||','|| SUBSTR(CONSTRAINT_NAME,0,7)||'_NUM' ||','||CONSTRAINT_TYPE||','||R_OWNER||','||R_CONSTRAINT_NAME||','||DELETE_RULE||','||STATUS||','||DEFERRABLE||','||DEFERRED||','||VALIDATED||','||GENERATED||','||BAD||','||RELY||','||INDEX_OWNER||','||INDEX_NAME||','||INVALID||','||VIEW_RELATED FROM DBA_CONSTRAINTS WHERE CONSTRAINT_NAME IN (select distinct(CONSTRAINT_NAME) FROM DBA_CONSTRAINTS MINUS select Distinct(CONSTRAINT_NAME) FROM DBA_CONS_COLUMNS) AND CONSTRAINT_NAME LIKE 'SYS%' AND OWNER = '&1' ORDER BY OWNER, TABLE_NAME, CONSTRAINT_NAME;

select 'xe.constraints_3' from dual;
SELECT OWNER||','||CONSTRAINT_NAME||','||TABLE_NAME||','||COLUMN_NAME||','||POSITION FROM DBA_CONS_COLUMNS WHERE CONSTRAINT_NAME IN (select Distinct(CONSTRAINT_NAME) FROM DBA_CONS_COLUMNS MINUS select distinct(CONSTRAINT_NAME) FROM DBA_CONSTRAINTS) and OWNER = '&1' ORDER BY OWNER, TABLE_NAME, CONSTRAINT_NAME;

select 'xe.indexes' from dual;
SELECT TABLE_OWNER||','||TABLE_NAME||','||TABLE_TYPE||','||INDEX_NAME||','||INDEX_TYPE||','||UNIQUENESS||','||COMPRESSION||','||PREFIX_LENGTH||','||TABLESPACE_NAME||','||MIN_EXTENTS||','||MAX_EXTENTS||','||PCT_INCREASE||','||INCLUDE_COLUMN||','||LOGGING||','||STATUS||','||DEGREE||','||INSTANCES||','||PARTITIONED||','||TEMPORARY||','||GENERATED||','||BUFFER_POOL||','||USER_STATS||','||PCT_DIRECT_ACCESS||','||ITYP_OWNER||','||ITYP_NAME||','||PARAMETERS||','||DOMIDX_STATUS||','||FUNCIDX_STATUS FROM DBA_INDEXES WHERE OWNER = '&1' ORDER BY TABLE_OWNER, TABLE_NAME, INDEX_NAME;

select 'xe.triggers' from dual;
SELECT TABLE_OWNER||','||TABLE_NAME||','||COLUMN_NAME||','||TRIGGER_NAME||','||TRIGGER_TYPE||','||TRIGGERING_EVENT||','||BASE_OBJECT_TYPE||','||REFERENCING_NAMES||','||STATUS||','||ACTION_TYPE FROM DBA_TRIGGERS WHERE OWNER = '&1' ORDER BY TABLE_OWNER, TABLE_NAME, COLUMN_NAME, TRIGGER_NAME;

select 'xe.views' from dual;
SELECT VIEW_NAME||','||TEXT_LENGTH||','||TYPE_TEXT_LENGTH||','||TYPE_TEXT||','||OID_TEXT_LENGTH||','||OID_TEXT||','||VIEW_TYPE_OWNER||','||VIEW_TYPE||','||SUPERVIEW_NAME FROM DBA_VIEWS WHERE OWNER = '&1' ORDER BY VIEW_NAME;

select 'xe.mviews' from dual;
SELECT OWNER||','||MVIEW_NAME||','||CONTAINER_NAME||','||QUERY_LEN||','||UPDATABLE||','||UPDATE_LOG||','||MASTER_ROLLBACK_SEG||','||MASTER_LINK||','||REWRITE_ENABLED||','||REWRITE_CAPABILITY||','||REFRESH_MODE||','||REFRESH_METHOD||','||BUILD_MODE||','||FAST_REFRESHABLE||','||LAST_REFRESH_TYPE||','||LAST_REFRESH_DATE||','||STALENESS||','||AFTER_FAST_REFRESH||','||UNKNOWN_PREBUILT||','||UNKNOWN_PLSQL_FUNC||','||UNKNOWN_EXTERNAL_TABLE||','||UNKNOWN_CONSIDER_FRESH||','||UNKNOWN_IMPORT||','||COMPILE_STATE||','||USE_NO_INDEX FROM DBA_MVIEWS WHERE OWNER = '&1' ORDER BY MVIEW_NAME;

select 'xe.synonyms' from dual;
SELECT SYNONYM_NAME||','||TABLE_OWNER||','||TABLE_NAME||','||nvl(DB_LINK,'<null>') FROM DBA_SYNONYMS WHERE OWNER = '&1' ORDER BY SYNONYM_NAME, TABLE_OWNER;

select 'xe.sequences' from dual;
SELECT SEQUENCE_NAME||','||MIN_VALUE||','||MAX_VALUE||','||INCREMENT_BY||','||CYCLE_FLAG||','||ORDER_FLAG||','||CACHE_SIZE||','||LAST_NUMBER FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER = '&1' ORDER BY SEQUENCE_NAME;

select 'xe.tabprevs' from dual;
SELECT OWNER||','||TABLE_NAME||','||GRANTOR||','||GRANTEE||','|| PRIVILEGE||','||GRANTABLE||','||HIERARCHY FROM DBA_TAB_PRIVS WHERE GRANTOR = '&1'  or GRANTEE = '&1' ORDER BY OWNER, TABLE_NAME, GRANTOR, GRANTEE, PRIVILEGE;

select 'xe.usrsysprevs' from dual;
SELECT GRANTEE||','||PRIVILEGE||','||ADMIN_OPTION FROM DBA_SYS_PRIVS WHERE GRANTEE = '&1' ORDER BY GRANTEE, PRIVILEGE;

select 'xe.usrroleprevs' from dual;
SELECT GRANTEE||','||GRANTED_ROLE||','||ADMIN_OPTION||','||DEFAULT_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = '&1' ORDER BY GRANTEE, GRANTED_ROLE;

select 'xe.procedures' from dual;
SELECT OBJECT_NAME||','||PROCEDURE_NAME||','||AGGREGATE||','||PIPELINED||','||IMPLTYPEOWNER||','||IMPLTYPENAME||','||PARALLEL||','||INTERFACE||','||DETERMINISTIC||','||AUTHID FROM DBA_PROCEDURES WHERE OWNER = '&1' ORDER BY OBJECT_NAME, PROCEDURE_NAME;

select 'xe.jobs' from dual;
SELECT JOB||','||LOG_USER||','||PRIV_USER||','||SCHEMA_USER||','||THIS_DATE||','||THIS_SEC||','||NEXT_DATE||','||NEXT_SEC||','||BROKEN||','||INTERVAL||','||FAILURES||','||WHAT||','||NLS_ENV||','||INSTANCE FROM DBA_JOBS WHERE SCHEMA_USER = '&1';

select 'xe.source' from dual;
SELECT NAME||','||TYPE||','||LINE||','||trim(TEXT) FROM DBA_SOURCE WHERE OWNER = '&1' ORDER BY TYPE, NAME, LINE;

exit;